# TensorTrade Default Configuration

# API settings
api:
  host: 0.0.0.0
  port: 8000
  debug: false

# Data settings
data:
  source: binance  # binance, csv, alpha_vantage, yahoo
  timeframes:
    - 1m
    - 5m
    - 15m
    - 30m
    - 1h
    - 4h
    - 1d
  symbols:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    - ADAUSDT
    - XRPUSDT
  csv_directory: data/

# Model settings
models:
  lstm:
    units: 128
    layers: 2
    dropout: 0.2
    sequence_length: 60
    prediction_horizon: 1
    target_type: price  # price, return, direction
    learning_rate: 0.001
    use_technical_indicators: true
    feature_columns:
      - open
      - high
      - low
      - close
      - volume
    loss: huber  # huber, mse

  rl:
    algorithm: ppo  # ppo, a2c, dqn
    policy: MlpPolicy
    window_size: 60
    reward_scaling: 0.01
    learning_rate: 0.0003
    gamma: 0.99
    n_steps: 2048
    batch_size: 64
    n_epochs: 10

  ensemble:
    lstm_config:
      units: 128
      layers: 2
      dropout: 0.2
      sequence_length: 60
      target_type: price

    rl_config:
      algorithm: ppo
      policy: MlpPolicy
      window_size: 60

    ensemble_config:
      lstm_weight: 0.6
      rl_weight: 0.4
      ensemble_method: voting  # voting, weighted

# Training settings
training:
  epochs: 100
  batch_size: 64
  validation_split: 0.2
  shuffle: true
  start_date: 2024-12-01
  end_date: 2025-03-01

# Backtest settings
backtest:
  initial_capital: 10000.0
  commission: 0.001  # 0.1%
  risk_per_trade: 0.02  # 2%
  stop_loss_pct: 0.02
  take_profit_pct: 0.04
  max_open_positions: 1
  start_date: 2025-02-01
  end_date: 2025-04-01

# Live trading settings
live:
  exchange: binance
  api_key: ""
  api_secret: ""
  initial_capital: 1000.0
  max_risk_per_trade: 0.02
  max_open_positions: 1
  max_daily_trades: 10
  max_drawdown_pct: 0.2
  position_sizing_method: fixed_percent
  allow_short: false
  min_position_size: 10.0
  update_interval_seconds: 60
  testnet: true

# Logging settings
logging:
  level: INFO
  file: logs/tensortrade.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size: 10485760  # 10MB
  backup_count: 5